[keyboard]
Key1 = "male_fr\\1.wav"
Key2 = "male_fr\\2.wav"
Key3 = "male_fr\\3.wav"
Key4 = "male_fr\\4.wav"
Key5 = "male_fr\\5.wav"
Key6 = "male_fr\\6.wav"
Key7 = "male_fr\\7.wav"
Key8 = "male_fr\\8.wav"
Key9 = "male_fr\\9.wav"
Key0 = "male_fr\\0.wav"
A = "male_fr\\A.wav"
B = "male_fr\\B.wav"
C = "male_fr\\C.wav"
D = "male_fr\\D.wav"
E = "male_fr\\E.wav"
F = "male_fr\\F.wav"
G = "male_fr\\G.wav"
H = "male_fr\\H.wav"
I = "male_fr\\I.wav"
J = "male_fr\\J.wav"
K = "male_fr\\K.wav"
L = "male_fr\\L.wav"
M = "male_fr\\M.wav"
N = "male_fr\\N.wav"
O = "male_fr\\O.wav"
P = "male_fr\\P.wav"
Q = "male_fr\\Q.wav"
R = "male_fr\\R.wav"
S = "male_fr\\S.wav"
T = "male_fr\\T.wav"
U = "male_fr\\U.wav"
V = "male_fr\\V.wav"
W = "male_fr\\W.wav"
X = "male_fr\\X.wav"
Y = "male_fr\\Y.wav"
Z = "male_fr\\Z.wav"
#Escape =
#F1 =
#F2 =
#F3 =
#F4 =
#F5 =
#F6 =
#F7 =
#F8 =
#F9 =
#F10 =
#F11 =
#F12 =
#F13 =
#F14 =
#F15 =
#F16 =
#F17 =
#F18 =
#F19 =
#F20 =
#F21 =
#F22 =
#F23 =
#F24 =
#Snapshot =
#Scroll =
#Pause =
#Insert =
#Home =
#Delete =
#End =
#PageDown =
#PageUp =
#Left =
#Up =
#Right =
#Down =
#Back =
#Return =
#Space =
#Compose =
#Caret =
#Numlock =
Numpad0 = "male_fr\\0.wav"
Numpad1 = "male_fr\\1.wav"
Numpad2 = "male_fr\\2.wav"
Numpad3 = "male_fr\\3.wav"
Numpad4 = "male_fr\\4.wav"
Numpad5 = "male_fr\\5.wav"
Numpad6 = "male_fr\\6.wav"
Numpad7 = "male_fr\\7.wav"
Numpad8 = "male_fr\\8.wav"
Numpad9 = "male_fr\\9.wav"
#AbntC1 =
#AbntC2 =
#NumpadAdd =
#Apostrophe =
#Apps =
#At =
#Ax =
#Backslash =
#Calculator =
#Capital =
#Colon =
#Comma =
#Convert =
#NumpadDecimal =
#NumpadDivide =
#Equals =
#Grave =
#Kana =
#Kanji =
#LAlt =
#LBracket =
#LControl =
#LShift =
#LWin =
#Mail =
#MediaSelect =
#MediaStop =
#Minus =
#NumpadMultiply =
#Mute =
#MyComputer =
#NavigateForward =
#NavigateBackward =
#NextTrack =
#NoConvert =
#NumpadComma =
#NumpadEnter =
#NumpadEquals =
#Oem102 =
#Period =
#PlayPause =
#Power =
#PrevTrack =
#RAlt =
#RBracket =
#RControl =
#RShift =
#RWin =
#Semicolon =
#Slash =
#Sleep =
#Stop =
#NumpadSubtract =
#Sysrq =
#Tab =
#Underline =
#Unlabeled =
#VolumeDown =
#VolumeUp =
#Wake =
#WebBack =
#WebFavorites =
#WebForward =
#WebHome =
#WebRefresh =
#WebSearch =
#WebStop =
#Yen =
#Copy =
#Paste =
#Cut =